mkdir datacards
mkdir infos_antibtag
mkdir infos_btag
mkdir pdfs
mkdir higgsCombineoutputs
mkdir workspaces
mkdir higgsCombineTests
mkdir higgsCombineBiases
mkdir comboLogs
mkdir brazilianFlags
mkdir mlfitoutputs
mkdir condorLogs
mkdir garbage
